export const dummyDoctorData = [
    {
      symptom: "Fever",
      image:'https://static.vecteezy.com/system/resources/previews/027/705/202/non_2x/sick-kids-has-fever-and-take-thermometer-in-mouth-vector.jpg',

      doctors: [
        {
          name: "Dr. Anil Kumar",
          degrees: ["MBBS", "MD"],
          type: "Physician",
          associatedSymptoms: ["Fever", "Cold", "Cough"],
          languages: ["Hindi", "English"],
          consultFees: 500,
          experience: 10,
          hospitalName: "Apollo Hospital",
        },
        {
          name: "Dr. Priya Sharma",
          degrees: ["MBBS", "DCH"],
          type: "Pediatrician",
          associatedSymptoms: ["Fever", "Vomiting", "Diarrhea"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 600,
          experience: 8,
          hospitalName: "Fortis Hospital",
        },
        {
          name: "Dr. Rajiv Singh",
          degrees: ["MBBS", "DEM"],
          type: "General Physician",
          associatedSymptoms: ["Fever", "Headache", "Body Pain"],
          languages: ["Hindi", "English"],
          consultFees: 450,
          experience: 12,
          hospitalName: "Max Healthcare",
        },
        {
          name: "Dr. Neha Verma",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Fever", "Fatigue", "Weakness"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 700,
          experience: 15,
          hospitalName: "AIIMS",
        },
      ],
    },
    {
      symptom: "Dark Circles",
      image:'https://media.istockphoto.com/id/1401641086/vector/dark-circles-under-eyes-vector-illustration.jpg?s=612x612&w=0&k=20&c=1TVi9HU3ISjteDSgJmosLD2DYnq9rlaKtOGNcbYj8GI=',
      doctors: [
        {
          name: "Dr. Meera Joshi",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Dark Circles", "Acne", "Skin Allergies"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 9,
          hospitalName: "Medanta Hospital",
        },
        {
          name: "Dr. Arun Patel",
          degrees: ["MBBS", "DVD"],
          type: "Cosmetologist",
          associatedSymptoms: ["Dark Circles", "Wrinkles", "Pigmentation"],
          languages: ["Hindi", "English", "Gujarati"],
          consultFees: 1000,
          experience: 11,
          hospitalName: "Columbia Asia",
        },
        {
          name: "Dr. Rekha Nair",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Dark Circles", "Fatigue", "Stress"],
          languages: ["Hindi", "English", "Malayalam"],
          consultFees: 500,
          experience: 7,
          hospitalName: "Narayana Health",
        },
        {
          name: "Dr. Sanjay Gupta",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Dark Circles", "Dry Skin", "Itching"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 13,
          hospitalName: "BLK Super Speciality",
        },
      ],
    },
    {
      symptom: "Vomiting",
      image:'https://img.freepik.com/free-vector/kid-sick-with-nausea-having-green-face_24877-83524.jpg',

      doctors: [
        {
          name: "Dr. Ramesh Verma",
          degrees: ["MBBS", "MD"],
          type: "Gastroenterologist",
          associatedSymptoms: ["Vomiting", "Nausea", "Abdominal Pain"],
          languages: ["Hindi", "English"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Sir Ganga Ram Hospital",
        },
        {
          name: "Dr. Sunita Reddy",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["Vomiting", "Diarrhea", "Dehydration"],
          languages: ["Hindi", "English", "Telugu"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Manipal Hospital",
        },
        {
          name: "Dr. Vikas Sharma",
          degrees: ["MBBS", "MD"],
          type: "Pediatrician",
          associatedSymptoms: ["Vomiting", "Fever", "Cough"],
          languages: ["Hindi", "English"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Rainbow Children's Hospital",
        },
        {
          name: "Dr. Pooja Desai",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Vomiting", "Food Poisoning", "Indigestion"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 800,
          experience: 12,
          hospitalName: "Lilavati Hospital",
        },
      ],
    },
    {
      symptom: "Headache",
      image:'https://static.vecteezy.com/system/resources/previews/007/925/255/non_2x/upset-young-man-having-a-headache-with-hand-squeezing-his-head-because-of-stress-migraine-and-having-worries-or-anxiety-problems-vector.jpg',

      doctors: [
        {
          name: "Dr. Rahul Mehta",
          degrees: ["MBBS", "MD"],
          type: "Neurologist",
          associatedSymptoms: ["Headache", "Migraine", "Vertigo"],
          languages: ["Hindi", "English"],
          consultFees: 1500,
          experience: 16,
          hospitalName: "All India Institute of Medical Sciences",
        },
        {
          name: "Dr. Shikha Jain",
          degrees: ["MBBS", "DPM"],
          type: "Psychiatrist",
          associatedSymptoms: ["Headache", "Stress", "Anxiety"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 1000,
          experience: 12,
          hospitalName: "Ram Manohar Lohia Hospital",
        },
        {
          name: "Dr. Ajay Kapoor",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Headache", "Cold", "Sinusitis"],
          languages: ["Hindi", "English"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Artemis Hospital",
        },
        {
          name: "Dr. Sneha Roy",
          degrees: ["MBBS", "MD"],
          type: "Neurosurgeon",
          associatedSymptoms: ["Headache", "Seizures", "Brain Injury"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 2000,
          experience: 18,
          hospitalName: "Jaslok Hospital",
        },
      ],
    },
    {
      symptom: "Cough",
      image:'https://media.istockphoto.com/id/1421878861/vector/young-ill-man-cough-isolated-vector-flat-style-cartoon-illustration.jpg?s=612x612&w=0&k=20&c=v0miTkTTxq7Z69yb85bqBkM7AULt1Rg5JK9YE-eua4I=',

      doctors: [
        {
          name: "Dr. Mohan Das",
          degrees: ["MBBS", "DTCD"],
          type: "Pulmonologist",
          associatedSymptoms: ["Cough", "Asthma", "Bronchitis"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 11,
          hospitalName: "Safdarjung Hospital",
        },
        {
          name: "Dr. Anjali Mishra",
          degrees: ["MBBS", "MD"],
          type: "Pediatrician",
          associatedSymptoms: ["Cough", "Fever", "Cold"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Kokilaben Hospital",
        },
        {
          name: "Dr. Vivek Singh",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Cough", "Throat Infection", "Allergies"],
          languages: ["Hindi", "English"],
          consultFees: 500,
          experience: 8,
          hospitalName: "Metro Hospital",
        },
        {
          name: "Dr. Divya Khanna",
          degrees: ["MBBS", "DTCD"],
          type: "Pulmonologist",
          associatedSymptoms: ["Cough", "Smoking Cessation", "Lung Cancer"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Escorts Heart Institute",
        },
      ],
    },
    {
      symptom: "Acne",
      image:'https://img.freepik.com/premium-vector/acne-vector-illustration-image_362642-348.jpg',

      doctors: [
        {
          name: "Dr. Deepak Verma",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Acne", "Pimples", "Scarring"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 10,
          hospitalName: "Max Super Speciality",
        },
        {
          name: "Dr. Ayesha Khan",
          degrees: ["MBBS", "DVD"],
          type: "Cosmetologist",
          associatedSymptoms: ["Acne", "Oily Skin", "Blackheads"],
          languages: ["Hindi", "English", "Urdu"],
          consultFees: 1100,
          experience: 12,
          hospitalName: "Fortis Escorts",
        },
        {
          name: "Dr. Prakash Rao",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Acne", "Hormonal Imbalance", "Stress"],
          languages: ["Hindi", "English", "Kannada"],
          consultFees: 600,
          experience: 8,
          hospitalName: "Sakra World Hospital",
        },
        {
          name: "Dr. Swati Jain",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Acne", "Eczema", "Psoriasis"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 13,
          hospitalName: "Indraprastha Apollo",
        },
      ],
    },
    {
      symptom: "Fatigue",
      image:'https://static.vecteezy.com/system/resources/previews/014/028/874/non_2x/chronic-tired-woman-exhausted-girl-female-character-feeling-weak-low-energy-state-physical-or-emotional-burnout-mental-fatigue-bad-health-symptom-free-vector.jpg',

      doctors: [
        {
          name: "Dr. Sunil Kumar",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Fatigue", "Weakness", "Anemia"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 11,
          hospitalName: "Global Hospitals",
        },
        {
          name: "Dr. Kavita Sharma",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["Fatigue", "Stress", "Depression"],
          languages: ["Hindi", "English", "Gujarati"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Asian Heart Institute",
        },
        {
          name: "Dr. Nitin Patil",
          degrees: ["MBBS", "MD"],
          type: "Endocrinologist",
          associatedSymptoms: ["Fatigue", "Thyroid Issues", "Weight Gain"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Lilavati Hospital",
        },
        {
          name: "Dr. Anjali Das",
          degrees: ["MBBS", "MD"],
          type: "Psychiatrist",
          associatedSymptoms: ["Fatigue", "Burnout", "Chronic Stress"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 1000,
          experience: 10,
          hospitalName: "Institute of Mental Health",
        },
      ],
    },
    {
      symptom: "Back Pain",
      image:'https://media.istockphoto.com/id/1253970413/vector/back-pain-treatment-vector-icon-illustration.jpg?s=612x612&w=0&k=20&c=DvcE6_bFwY8G1wwMZMl4rQICgABt6c71pr2g8iAQTVE=',

      doctors: [
        {
          name: "Dr. Ashok Singh",
          degrees: ["MBBS", "MS Ortho"],
          type: "Orthopedic Surgeon",
          associatedSymptoms: ["Back Pain", "Joint Pain", "Arthritis"],
          languages: ["Hindi", "English"],
          consultFees: 1500,
          experience: 18,
          hospitalName: "AIIMS",
        },
        {
          name: "Dr. Ritu Chawla",
          degrees: ["MBBS", "MD"],
          type: "Physiotherapist",
          associatedSymptoms: ["Back Pain", "Muscle Strain", "Posture Issues"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 700,
          experience: 10,
          hospitalName: "Fortis Hospital",
        },
        {
          name: "Dr. Vikram Bhatia",
          degrees: ["MBBS", "MS Ortho"],
          type: "Orthopedic Surgeon",
          associatedSymptoms: ["Back Pain", "Disc Problems", "Sciatica"],
          languages: ["Hindi", "English"],
          consultFees: 1800,
          experience: 20,
          hospitalName: "Apollo Hospital",
        },
        {
          name: "Dr. Sonia Kapoor",
          degrees: ["MBBS", "MD"],
          type: "Rheumatologist",
          associatedSymptoms: ["Back Pain", "Autoimmune Disorders", "Inflammation"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 1400,
          experience: 15,
          hospitalName: "Medanta Hospital",
        },
      ],
    },
    {
      symptom: "Stomach Pain",
      image:'https://img.freepik.com/free-vector/stomachache-concept-illustration_114360-6591.jpg',

      doctors: [
        {
          name: "Dr. Rajesh Kumar",
          degrees: ["MBBS", "MD"],
          type: "Gastroenterologist",
          associatedSymptoms: ["Stomach Pain", "Ulcers", "Acidity"],
          languages: ["Hindi", "English"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Sir Ganga Ram Hospital",
        },
        {
          name: "Dr. Neetu Sharma",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["Stomach Pain", "Food Poisoning", "Indigestion"],
          languages: ["Hindi", "English", "Telugu"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Manipal Hospital",
        },
        {
          name: "Dr. Vinay Singh",
          degrees: ["MBBS", "MD"],
          type: "Pediatrician",
          associatedSymptoms: ["Stomach Pain", "Colic", "Constipation"],
          languages: ["Hindi", "English"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Rainbow Children's Hospital",
        },
        {
          name: "Dr. Preeti Desai",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Stomach Pain", "IBS", "Crohn's Disease"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 800,
          experience: 12,
          hospitalName: "Lilavati Hospital",
        },
      ],
    },
    {
      symptom: "Insomnia",
      image:'https://media.istockphoto.com/id/1680182911/vector/a-woman-lies-in-bed-and-cannot-fall-asleep-mental-disorder-concept-depression-insomnia.jpg?s=612x612&w=0&k=20&c=Ks8zmDz7BKmj5LaoPL3OMbMXs1mdBJ-j61ACbeuxuSc=',

      doctors: [
        {
          name: "Dr. Rohit Verma",
          degrees: ["MBBS", "MD"],
          type: "Psychiatrist",
          associatedSymptoms: ["Insomnia", "Sleep Disorders", "Anxiety"],
          languages: ["Hindi", "English"],
          consultFees: 1000,
          experience: 12,
          hospitalName: "Ram Manohar Lohia Hospital",
        },
        {
          name: "Dr. Shruti Jain",
          degrees: ["MBBS", "DPM"],
          type: "Clinical Psychologist",
          associatedSymptoms: ["Insomnia", "Stress", "Depression"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 800,
          experience: 10,
          hospitalName: "VIMHANS",
        },
        {
          name: "Dr. Ajay Mehta",
          degrees: ["MBBS", "MD"],
          type: "Neurologist",
          associatedSymptoms: ["Insomnia", "Migraine", "Nerve Pain"],
          languages: ["Hindi", "English"],
          consultFees: 1500,
          experience: 16,
          hospitalName: "AIIMS",
        },
        {
          name: "Dr. Anjali Roy",
          degrees: ["MBBS", "MD"],
          type: "Sleep Specialist",
          associatedSymptoms: ["Insomnia", "Snoring", "Sleep Apnea"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 2000,
          experience: 18,
          hospitalName: "Jaslok Hospital",
        },
      ],
    },
    {
      symptom: "Diarrhea",
      image:'https://media.istockphoto.com/id/1250292207/vector/sick-man-with-stomachache-touching-belly.jpg?s=612x612&w=0&k=20&c=Tj-1nzfCnp3lPkFTx4ed4y4m3gp58FZ2EVyOlIUU_-g=',

      doctors: [
        {
          name: "Dr. Rahul Sharma",
          degrees: ["MBBS", "MD"],
          type: "Gastroenterologist",
          associatedSymptoms: ["Diarrhea", "Food Poisoning", "Dehydration"],
          languages: ["Hindi", "English"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Sir Ganga Ram Hospital",
        },
        {
          name: "Dr. Suman Reddy",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["Diarrhea", "Vomiting", "Stomach Infections"],
          languages: ["Hindi", "English", "Telugu"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Manipal Hospital",
        },
        {
          name: "Dr. Vikas Kumar",
          degrees: ["MBBS", "MD"],
          type: "Pediatrician",
          associatedSymptoms: ["Diarrhea", "Fever", "Cold"],
          languages: ["Hindi", "English"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Rainbow Children's Hospital",
        },
        {
          name: "Dr. Pooja Desai",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Diarrhea", "IBS", "Crohn's Disease"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 800,
          experience: 12,
          hospitalName: "Lilavati Hospital",
        },
      ],
    },
    {
      symptom: "Allergies",
      image:'https://img.freepik.com/free-vector/pollen-allergy-concept-illustration_114360-6586.jpg?semt=ais_hybrid',

      doctors: [
        {
          name: "Dr. Ankit Verma",
          degrees: ["MBBS", "MD"],
          type: "Allergist",
          associatedSymptoms: ["Allergies", "Asthma", "Hay Fever"],
          languages: ["Hindi", "English"],
          consultFees: 1000,
          experience: 12,
          hospitalName: "AIIMS",
        },
        {
          name: "Dr. Shweta Jain",
          degrees: ["MBBS", "DCH"],
          type: "Pediatrician",
          associatedSymptoms: ["Allergies", "Skin Rashes", "Food Sensitivity"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 800,
          experience: 10,
          hospitalName: "Fortis Hospital",
        },
        {
          name: "Dr. Ajay Kapoor",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Allergies", "Cold", "Sinusitis"],
          languages: ["Hindi", "English"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Artemis Hospital",
        },
        {
          name: "Dr. Sneha Roy",
          degrees: ["MBBS", "MD"],
          type: "Dermatologist",
          associatedSymptoms: ["Allergies", "Eczema", "Psoriasis"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 900,
          experience: 13,
          hospitalName: "Jaslok Hospital",
        },
      ],
    },
    {
      symptom: "Joint Pain",
      image:'https://previews.123rf.com/images/nazarii1207/nazarii12072001/nazarii1207200100090/138603339-vector-illstration-of-joint-pain-icon-flat-design.jpg',

      doctors: [
        {
          name: "Dr. Ashok Singh",
          degrees: ["MBBS", "MS Ortho"],
          type: "Orthopedic Surgeon",
          associatedSymptoms: ["Joint Pain", "Arthritis", "Knee Pain"],
          languages: ["Hindi", "English"],
          consultFees: 1500,
          experience: 18,
          hospitalName: "AIIMS",
        },
        {
          name: "Dr. Ritu Chawla",
          degrees: ["MBBS", "MD"],
          type: "Physiotherapist",
          associatedSymptoms: ["Joint Pain", "Muscle Strain", "Posture Issues"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 700,
          experience: 10,
          hospitalName: "Fortis Hospital",
        },
        {
          name: "Dr. Vikram Bhatia",
          degrees: ["MBBS", "MS Ortho"],
          type: "Orthopedic Surgeon",
          associatedSymptoms: ["Joint Pain", "Disc Problems", "Sciatica"],
          languages: ["Hindi", "English"],
          consultFees: 1800,
          experience: 20,
          hospitalName: "Apollo Hospital",
        },
        {
          name: "Dr. Sonia Kapoor",
          degrees: ["MBBS", "MD"],
          type: "Rheumatologist",
          associatedSymptoms: ["Joint Pain", "Autoimmune Disorders", "Inflammation"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 1400,
          experience: 15,
          hospitalName: "Medanta Hospital",
        },
      ],
    },
    {
      symptom: "Hair Loss",
      image:'https://media.istockphoto.com/id/1256307836/vector/female-character-with-a-comb-loses-hair.jpg?s=612x612&w=0&k=20&c=SG42SH2phNJ8DE-4qyBLexlZFWfZzUwWZKBpmt9tnQo=',

      doctors: [
        {
          name: "Dr. Deepak Verma",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Hair Loss", "Dandruff", "Itchy Scalp"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 10,
          hospitalName: "Max Super Speciality",
        },
        {
          name: "Dr. Ayesha Khan",
          degrees: ["MBBS", "DVD"],
          type: "Cosmetologist",
          associatedSymptoms: ["Hair Loss", "Thinning Hair", "Hair Damage"],
          languages: ["Hindi", "English", "Urdu"],
          consultFees: 1100,
          experience: 12,
          hospitalName: "Fortis Escorts",
        },
        {
          name: "Dr. Prakash Rao",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Hair Loss", "Hormonal Imbalance", "Stress"],
          languages: ["Hindi", "English", "Kannada"],
          consultFees: 600,
          experience: 8,
          hospitalName: "Sakra World Hospital",
        },
        {
          name: "Dr. Swati Jain",
          degrees: ["MBBS", "DDVL"],
          type: "Dermatologist",
          associatedSymptoms: ["Hair Loss", "Eczema", "Psoriasis"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 13,
          hospitalName: "Indraprastha Apollo",
        },
      ],
    },
    {
      symptom: "Dizziness",
      image:'https://www.shutterstock.com/image-vector/dizziness-man-closed-eyes-holds-600nw-2148113673.jpg',

      doctors: [
        {
          name: "Dr. Rahul Mehta",
          degrees: ["MBBS", "MD"],
          type: "Neurologist",
          associatedSymptoms: ["Dizziness", "Vertigo", "Migraine"],
          languages: ["Hindi", "English"],
          consultFees: 1500,
          experience: 16,
          hospitalName: "All India Institute of Medical Sciences",
        },
        {
          name: "Dr. Shikha Jain",
          degrees: ["MBBS", "DPM"],
          type: "Psychiatrist",
          associatedSymptoms: ["Dizziness", "Stress", "Anxiety"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 1000,
          experience: 12,
          hospitalName: "Ram Manohar Lohia Hospital",
        },
        {
          name: "Dr. Ajay Kapoor",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Dizziness", "Cold", "Sinusitis"],
          languages: ["Hindi", "English"],
          consultFees: 600,
          experience: 10,
          hospitalName: "Artemis Hospital",
        },
        {
          name: "Dr. Sneha Roy",
          degrees: ["MBBS", "MD"],
          type: "Neurosurgeon",
          associatedSymptoms: ["Dizziness", "Seizures", "Brain Injury"],
          languages: ["Hindi", "English", "Tamil"],
          consultFees: 2000,
          experience: 18,
          hospitalName: "Jaslok Hospital",
        },
      ],
    },
    {
      symptom: "Shortness of Breath",
      image:'https://media.istockphoto.com/id/1757962048/vector/shortness-of-breath-and-pulmonary-disease-icon.jpg?s=612x612&w=0&k=20&c=nE7UwdpWeJwKHcd1-msPfF2zlRwu1mZucIRgse1cYiI=',

      doctors: [
        {
          name: "Dr. Mohan Das",
          degrees: ["MBBS", "DTCD"],
          type: "Pulmonologist",
          associatedSymptoms: ["Shortness of Breath", "Asthma", "Bronchitis"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 11,
          hospitalName: "Safdarjung Hospital",
        },
        {
          name: "Dr. Anjali Mishra",
          degrees: ["MBBS", "MD"],
          type: "Pediatrician",
          associatedSymptoms: ["Shortness of Breath", "Fever", "Cold"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Kokilaben Hospital",
        },
        {
          name: "Dr. Vivek Singh",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Shortness of Breath", "Throat Infection", "Allergies"],
          languages: ["Hindi", "English"],
          consultFees: 500,
          experience: 8,
          hospitalName: "Metro Hospital",
        },
        {
          name: "Dr. Divya Khanna",
          degrees: ["MBBS", "DTCD"],
          type: "Pulmonologist",
          associatedSymptoms: ["Shortness of Breath", "Smoking Cessation", "Lung Cancer"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Escorts Heart Institute",
        },
      ],
    },
    {
      symptom: "High Blood Pressure",
      image:'https://media.istockphoto.com/id/1435670429/vector/hypertension-high-blood-pressure-treatment-big-human-heart-with-sphygmomanometer-medical.jpg?s=612x612&w=0&k=20&c=YDwVNt4oTtAL_ZxEePUTJ74Y1lefgNnctAEWkNQLYfg=',

      doctors: [
        {
          name: "Dr. Sunil Kumar",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["High Blood Pressure", "Hypertension", "Heart Disease"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 11,
          hospitalName: "Global Hospitals",
        },
        {
          name: "Dr. Kavita Sharma",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["High Blood Pressure", "Stress", "Obesity"],
          languages: ["Hindi", "English", "Gujarati"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Asian Heart Institute",
        },
        {
          name: "Dr. Nitin Patil",
          degrees: ["MBBS", "MD"],
          type: "Cardiologist",
          associatedSymptoms: ["High Blood Pressure", "Heart Attack", "Stroke"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Lilavati Hospital",
        },
        {
          name: "Dr. Anjali Das",
          degrees: ["MBBS", "MD"],
          type: "Endocrinologist",
          associatedSymptoms: ["High Blood Pressure", "Thyroid Issues", "Diabetes"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 1000,
          experience: 10,
          hospitalName: "Institute of Mental Health",
        },
      ],
    },
    {
      symptom: "Chest Pain",
      image:'https://media.istockphoto.com/id/1757972595/vector/man-having-chest-pain-icon.jpg?s=612x612&w=0&k=20&c=9AzVNogozq1y9kGkpQVnd24lBLs33zmmfgV17CaOpbQ=',

      doctors: [
        {
          name: "Dr. Mohan Das",
          degrees: ["MBBS", "DTCD"],
          type: "Cardiologist",
          associatedSymptoms: ["Chest Pain", "Heart Attack", "Angina"],
          languages: ["Hindi", "English"],
          consultFees: 900,
          experience: 11,
          hospitalName: "Safdarjung Hospital",
        },
        {
          name: "Dr. Anjali Mishra",
          degrees: ["MBBS", "MD"],
          type: "General Physician",
          associatedSymptoms: ["Chest Pain", "Acidity", "Stomach Issues"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Kokilaben Hospital",
        },
        {
          name: "Dr. Vivek Singh",
          degrees: ["MBBS", "MD"],
          type: "Pulmonologist",
          associatedSymptoms: ["Chest Pain", "Breathing Issues", "Lung Infections"],
          languages: ["Hindi", "English"],
          consultFees: 500,
          experience: 8,
          hospitalName: "Metro Hospital",
        },
        {
          name: "Dr. Divya Khanna",
          degrees: ["MBBS", "DTCD"],
          type: "Cardiologist",
          associatedSymptoms: ["Chest Pain", "Heart Disease", "High Blood Pressure"],
          languages: ["Hindi", "English", "Punjabi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Escorts Heart Institute",
        },
      ],
    },
    {
      symptom: "Swelling",
      image:'https://static.vecteezy.com/system/resources/previews/004/899/652/non_2x/human-feet-and-leg-swelling-illustration-on-the-topic-of-medicine-vector.jpg',

      doctors: [
        {
          name: "Dr. Sunil Kumar",
          degrees: ["MBBS", "MD"],
          type: "Internal Medicine Specialist",
          associatedSymptoms: ["Swelling", "Edema", "Kidney Issues"],
          languages: ["Hindi", "English"],
          consultFees: 800,
          experience: 11,
          hospitalName: "Global Hospitals",
        },
        {
          name: "Dr. Kavita Sharma",
          degrees: ["MBBS", "DGO"],
          type: "General Physician",
          associatedSymptoms: ["Swelling", "Injury", "Inflammation"],
          languages: ["Hindi", "English", "Gujarati"],
          consultFees: 700,
          experience: 9,
          hospitalName: "Asian Heart Institute",
        },
        {
          name: "Dr. Nitin Patil",
          degrees: ["MBBS", "MD"],
          type: "Nephrologist",
          associatedSymptoms: ["Swelling", "Kidney Stones", "Urinary Issues"],
          languages: ["Hindi", "English", "Marathi"],
          consultFees: 1200,
          experience: 14,
          hospitalName: "Lilavati Hospital",
        },
        {
          name: "Dr. Anjali Das",
          degrees: ["MBBS", "MD"],
          type: "Rheumatologist",
          associatedSymptoms: ["Swelling", "Joint Pain", "Autoimmune Disorders"],
          languages: ["Hindi", "English", "Bengali"],
          consultFees: 1000,
          experience: 10,
          hospitalName: "Institute of Mental Health",
        },
      ],
    },
  ];